// Utility function to interact with Gemini API

export async function evaluateSubmissionWithGemini(apiKey, rubric, submissionContent) {
  const prompt = `You are an expert teacher grading a student's submission.
Below is the rubric or expected standard:
---
${rubric}
---

And here is the student's submission content (extracted text):
---
${submissionContent}
---

Based on the rubric, evaluate the student's work. Provide:
1. A suggested numerical grade (e.g., 85/100 or what the rubric specifies).
2. Constructive feedback explaining what they did well and where they can improve.
3. Be direct, professional, and clear.

Format your response in Markdown.`;

  const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      contents: [{
        parts: [{ text: prompt }]
      }]
    })
  });

  if (!response.ok) {
    throw new Error(`Gemini API Error: ${response.statusText}`);
  }

  const data = await response.json();
  
  if (data.candidates && data.candidates.length > 0) {
    return data.candidates[0].content.parts[0].text;
  }
  
  throw new Error("No response generated by Gemini.");
}
