// Utility function to interact with Gemini API

export async function evaluateSubmissionWithGemini(apiKey, rubric, submissionContent) {
  const prompt = `You are an expert teacher grading a student's submission.
Below is the rubric or expected standard:
---
${rubric}
---

And here is the student's submission content (extracted text):
---
${submissionContent}
---

Based on the rubric, evaluate the student's work. Provide a JSON object with EXACTLY two keys:
- "grade": a numerical value representing the grade out of the max points (e.g. 85) or null if no grade.
- "feedback": Constructive feedback explaining what they did well and where they can improve.

Ensure the response is valid JSON and nothing else. Do not include markdown code block syntax around the JSON.`;

  const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      contents: [{
        parts: [{ text: prompt }]
      }]
    })
  });

  if (!response.ok) {
    throw new Error(`Gemini API Error: ${response.statusText}`);
  }

  const data = await response.json();
  
  if (data.candidates && data.candidates.length > 0) {
    let textResult = data.candidates[0].content.parts[0].text;
    textResult = textResult.replace(/```json/g, '').replace(/```/g, '').trim();
    try {
      return JSON.parse(textResult);
    } catch (e) {
      return { grade: null, feedback: textResult };
    }
  }
  
  throw new Error("No response generated by Gemini.");
}
